$LOAD_PATH << File.expand_path("../../lib", __FILE__)
require "rails2_asset_pipeline/tasks"

task :environment do
  # simulate loading of rails
  require "pathname"

  module Rails
    def self.root
      Pathname.new(File.expand_path("..", __FILE__))
    end
  end

  require "rails2_asset_pipeline"
end
